ARG ZPZ_VERSION
ARG PYTHON_VERSION


FROM zpz:${ZPZ_VERSION} as zpz-dist-img
# No op. Needed b/c '--from' can't take variables.


FROM python:${PYTHON_VERSION}-slim

COPY --from=zpz-dist-img /zpz-dist /tmp/zpz-dist

RUN cd /tmp/zpz-dist \
    && python -m pip install --no-index --find-links=./ -r requirements.txt \
    && python -m pip install --find-links=./ zpz

# Install test dependencies in order to run tests.
RUN python -m pip install -r /tmp/zpz-dist/requirements-test.txt
