FROM zpz-test:latest AS base

RUN cd /zpz-src \
        && mkdir /zpz-dist \
        && cp requirements.txt /zpz-dist/ \
        && cp requirements-test.txt /zpz-dist/ \
        && mv tests /zpz-dist/ \
        && python setup.py -q sdist -d /zpz-dist \
        && python setup.py -q bdist_wheel -d /zpz-dist \
        && python -m pip wheel -r requirements.txt -w /zpz-dist


FROM alpine:3

COPY --from=base /zpz-dist /zpz-dist

