FROM quay.io/pypa/manylinux2010_x86_64
USER root

ARG PROJ
ARG PLAT=manylinux2010_x86_64

ENV PROJ=${PROJ}
ENV BUILDDIR=/build

ENV PYVER=cp38-cp38
ENV PYBIN=/opt/python/cp38-cp38/bin
ENV PIP=${PYBIN}/pip

COPY . /src/

RUN ( \
        ${PIP} install build; \
        ${PIP} install -r /src/requirements-test.txt; \
        ${PIP} install -e /src/; \
        ${PIP} uninstall -y ${PROJ}; \
        echo; \
        echo ---- building in $pyver ----; \
        echo; \
        ${PYBIN}/python -m build -o ${BUILDDIR} /src/ || exit 1; \
        for wheel in ${BUILDDIR}/*.whl; do \
            if ! auditwheel show "$wheel"; then \
                echo "Skipping non-platform wheel $wheel"; \
            else \
                auditwheel repair "$wheel" --plat "$PLAT" -w ${BUILDDIR}; \
            fi \
        done; \
        echo; \
        echo ---- testing in $pyver ----; \
        echo; \
        ${PIP} install ${PROJ} --no-index -f ${BUILDDIR} || exit 1; \
        (cd "$HOME"; "${PYBIN}/python" -m pytest /src/tests) || exit 1; \
)
