#!/bin/bash

# Run this script within the container launched by `./run`.
# If everything goes well, the built package is in dist/.
# Outside of Docker, upload the package to PyPI by
#   $ python3 -m twine upload dist/*


set -e

./run-tests || exit 1

rm -rf dist/
python -m build ./
rm -rf ./src/*egg-info

