#!/usr/bin/env bash

if [[ $(git branch --show-current) != master ]]; then
    >&2 echo Please switch to branch '"master"' to make release
    exit 1
fi

./run-tests || exit 1

version=$(docker run --rm zpz-test:latest pip show zpz | grep Version)
version=${version#* }
echo
echo "zpz version: ${version}"
echo

docker build -t zpz:${version} - <<EOF
FROM alpine:3
COPY --from=zpz-test:latest /zpz-dist /zpz-dist
EOF
[ $? -eq 0 ] || exit 1

docker build \
    -f Dockerfile_test_release \
    --build-arg ZPZ_VERSION="${version}" \
    -t zpz-test-release:latest \
    ./
if [ $? -ne 0 ]; then
    docker rmi zpz:${version}
fi

echo
echo Successfully created release zpz:${version}
