#!/bin/bash

# Run this script within the container launched by `./run`.


set -e


# Infer package name:
rm -rf src/*egg-info
proj="$(ls src/)"
if [[ $proj = *' '* ]]; then
    >&2 echo "unable to infer project name"
    exit 1
fi
PROJ=${proj%/}


SRC=$(pwd)/src
TESTS=$(pwd)/tests


echo
echo --- running bandit ---
echo
bandit -r -lll ${SRC}/${PROJ}
bandit -r -lll ${TESTS}

echo
echo --- running flake8 ---
echo
python -m flake8 --ignore E501,W503 ${SRC}/${PROJ}

echo
echo --- running mypy ---
echo
python -m mypy --show-error-codes --disable-error-code import ${SRC}/${PROJ} || true

echo
echo --- running pylint ---
echo
python -m pylint --disable=C0103,C0114,C0115,C0116,C0301,C0303,C0305,R0903 ${SRC}/${PROJ} || pylint-exit $?
# python -m pylint --errors-only ${SRC} || pylint-exit $?


echo
echo --- running tests ---
echo
coverage run --data-file=/tmp/.coverage --source=${SRC} -m pytest ${TESTS}
echo
echo --- reporting coverage ---
echo
coverage report --data-file=/tmp/.coverage
