#!/usr/bin/env sh

( cd ../ && ./run-tests ) || exit 1

version=$(docker run --rm zpz-test:latest pip show zpz | grep Version)
version=${version#* }
echo "zpz version: ${version}"

docker build . \
    -f Dockerfile_release \
    -t zpz:${version}
