#!/usr/bin/env sh
if [ "$#" -ne 1 ]; then
    >&2 echo "missing zpz-version"
    exit 1
fi
zpz_version="$1"

docker build \
    -f Dockerfile_test_release \
    --build-arg ZPZ_VERSION="${zpz_version}" \
    -t zpz-test-release:latest \
    ./
